### PR TITLE
Added support for multiple gist deletion, closes #22

### LINKED ISSUE #22: Delete multiple gists
Currently 'gist' only supports the deletion of one gist at a time. Enable it to take multiple identifiers to delete.

### PR DESCRIPTION
**Pull request by SeriousBug**
Works properly, and passes tests. Sorry for opening pull requests twice.

### CODE REVIEW

**Comment by SeriousBug** [comment]
Made the changes we talked about, tests are passing and multiple deletion works. Thanks for the suggestions.

**Comment by jdowner** [comment]
One last thing, would you mind rebasing those commits into one to remove the merge commit and commit that does not pass the tests. Thanks!

**Comment by SeriousBug** [comment]
I rebased the commits. I didn't know about rebase, thanks for teaching something new. :)

**Comment by jdowner** [comment]
Cool! I think I would be lost without rebasing :)

**Pull request merged**
