### PR TITLE
Added the ability to edit a gist description

### PR DESCRIPTION
**Pull request by karanparikh**
Added the ability to edit a gist description.
Tested manually

### CODE REVIEW

**Comment by jdowner** [comment]
Thanks for the PR Karan! I have added some comments and I hope they make sense. Let me know if you have any questions.

**Comment by karanparikh** [comment]
Thanks for the feedback @jdowner 
I like your suggestion of having a separate description command. I think I will go with that.

**Comment by karanparikh** [comment]
Thanks for the feedback @jdowner. I will address them later tonight and send out a new patch.

**Comment by jdowner** [comment]
Rebase your changes to remove the merge commit and make that one change regarding printing the description and I will merge this.

**Comment by jdowner** [comment]
Thanks Karan!

**Pull request merged**
