### PR TITLE
Add completion support for the Fish shell

### PR DESCRIPTION
**Pull request by ejmr**
Signed-off-by: Eric James Michael Ritz <ejmr@plutono.com>

### CODE REVIEW

**Comment by ejmr** [comment]
I have corrected the patch.  Sorry about the initial mistake by rushing.  Great tool by the way :)

**Comment by ejmr** [comment]
Do you want me to fix those two "Pints" typos?

**Comment by jdowner** [comment]
Oops! No, that's fine I just push a chaser commit.

**Comment by ejmr** [comment]
Thank you.

**Pull request merged**
